### PR TITLE
AdfsFarm: Add parameters to set certificates based on their names

### PR DESCRIPTION
**Pull request by Yvand**
#### Pull Request (PR) description

I use DSC to completely provision Active Directory, including the creation of AD CS and AD FS.
The certificates used by AD FS are issued by AD CS.
In this scenario, the thumbprint of those certificates are know only at run-time, so I cannot set the thumbprint at design-time.
For this reason, I used the certificates names instead, and I updated AdfsFarm to support it

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/x-guardian/adfsdsc/48)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Hi @Yvand, thanks for raising the PR. Good to know that the module is being used. Can you take a look at the PR validation checks that are failing? This will also need the unit tests extending to cover the new code.

**Comment by Yvand** [comment]
@X-Guardian, sure it is, you did very good work !
I'm happy to validate all the checks but I wanted to validate that you would approve those changes before I spend time on this.
Specifically, are you fine with the (necessary) removal of the required flag for the parameter CertificateThumbprint?

**Comment by Yvand** [comment]
@X-Guardian ok, this is more complicated than I thought.
How can I find exactly what tests fail? I see it's in Tests\Unit\MSFT_AdfsFarm.tests.ps1 but it contains many tests, and the CI output is not easy to read.

**Comment by X-Guardian** [comment]
If you look at the `HQRM / Run HQRM Test` and `Unit / Run Unit Test` output in Azure Pipelines and search for `[-]` you will see where the tests are faiilng.

**Review by X-Guardian — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-guardian/adfsdsc/48)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @Yvand)

___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 113 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-wszx8AAXhueGxGOi:-MY-wszx8AAXhueGxGOj:b-my2f42) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L113)):*
> ```PowerShell
> 
>         [System.String]
>         $CertificateName
> ```

`CertificateName` and `CertificateThumbprint` are no longer needed as parameters on `Get-TargetResource` as they are not mandatory.
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 214 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-xnja439qpos1jPC8:-MY-xnja439qpos1jPC9:buaa7kq) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L214)):*
> ```PowerShell
>             FederationServiceName         = $adfsProperties.HostName
>             CertificateThumbprint         = $certificateThumbprint
>             CertificateName               = $certificateName
> ```

Need to add `SigningCertifcateName` and `DecryptionCertificateName` parameters. Values for these can be obtained using the `Get-AdfsCertificate -CertificateType` cmdlet.
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 229 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-yAbs1oPSDX_wsKl8:-MY-yAbs1oPSDX_wsKl9:b-9t49xa) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L229)):*
> ```PowerShell
>         $returnValue = @{
>             FederationServiceName         = $FederationServiceName
>             CertificateThumbprint         = $CertificateThumbprint
> ```

`CertificateThumbprint` and `CertificateName` should both be returned `$null`. Need to add `SigningCertificateName` and`DecryptionCertificateName`
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 367 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-yaN89QTMP94kgh5M:-MY-yaN89QTMP94kgh5N:bsw0eni) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L367)):*
> ```PowerShell
>         CertificateThumbprint = $CertificateThumbprint
>         Credential            = $Credential
>         CertificateName       = $CertificateName
> ```

`CertificateName` and `CertiifcateThumbprint` parameters not needed.
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 395 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-yfk22L1eOry3S6Me:-MY-yfk22L1eOry3S6Mf:ba09o61) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L395)):*
> ```PowerShell
>         if ($PSBoundParameters.ContainsKey('CertificateName'))
>         {
>             $siteCert = Get-ChildItem -Path "cert:\LocalMachine\My\" -DnsName $CertificateName
> ```

Need to raise an `InvalidArgumentException` if the certificate does not exist. It may also match multiple certificates. Suggest logic is added to use the one with the latest `NotAfter` date, as long as the `NotBefore` date has passed.
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 402 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-yxxQ2aXPdlOxW8dR:-MY-yxxQ2aXPdlOxW8dS:ba09o61) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L402)):*
> ```PowerShell
>         if ($PSBoundParameters.ContainsKey('SigningCertificateName'))
>         {
>             $signingCert = Get-ChildItem -Path "cert:\LocalMachine\My\" -DnsName $SigningCertificateName
> ```

Need to raise an `InvalidArgumentException` if the certificate does not exist. It may also match multiple certificates. Suggest logic is added to use the one with the latest `NotAfter` date, as long as the `NotBefore` date has passed.
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 409 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-yyay0TA4xMMkJq9u:-MY-yyay0TA4xMMkJq9v:ba09o61) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L409)):*
> ```PowerShell
>         if ($PSBoundParameters.ContainsKey('DecryptionCertificateName'))
>         {
>             $decryptionCert = Get-ChildItem -Path "cert:\LocalMachine\My\" -DnsName $DecryptionCertificateName
> ```

Need to raise an `InvalidArgumentException` if the certificate does not exist. It may also match multiple certificates. Suggest logic is added to use the one with the latest `NotAfter` date, as long as the `NotBefore` date has passed.
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1, line 520 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-z2VL8-UkuurEt9R0:-MY-z2VL8-UkuurEt9R1:bsw0eni) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L520)):*
> ```PowerShell
>         CertificateThumbprint = $CertificateThumbprint
>         Credential            = $Credential
>         CertificateName       = $CertificateName
> ```

`CertificateName` and `CertiifcateThumbprint` parameters not needed.
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof, line 14 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY0ettGAOd3PBaJkxFY:-MY0ettHBbm9C6rzbKiN:b-vxdukg) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof#L14)):*
> ```
>     [Write, EmbeddedInstance("MSFT_KeyValuePair"), Description("Specifies the Admin Configuration")] String AdminConfiguration[];
>     [Read, Description("The state of the ADFS Farm.")] String Ensure;
>     [Write, Description("Specifies the name of the certificate to use for HTTPS bindings and service communication for ADFS. This value should match the thumbprint of a valid certificate in the Local Computer certificate store.")] String CertificateName;
> ```

We should call this parameter `CertifcateDnsName` here and everywhere referenced and update the description to  "...This value should match the DNS name of a valid certificate..."
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof, line 15 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY0f2J41aTuUngVmPQJ:-MY0f2J41aTuUngVmPQK:bfclipv) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof#L15)):*
> ```
>     [Read, Description("The state of the ADFS Farm.")] String Ensure;
>     [Write, Description("Specifies the name of the certificate to use for HTTPS bindings and service communication for ADFS. This value should match the thumbprint of a valid certificate in the Local Computer certificate store.")] String CertificateName;
>     [Write, Description("Specifies the name of the signing certificate for ADFS. This value should match the name of a valid certificate in the Local Computer certificate store.")] String SigningCertificateName;
> ```

We should call this parameter `SigningCertifcateDnsName` here and everywhere referenced and update the description to "...This value should match the DNS name of a valid certificate..."
___
*[source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof, line 16 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY0f2nX5ZxtaRMRR3Nh:-MY0f2nX5ZxtaRMRR3Ni:bddlbzv) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof#L16)):*
> ```
>     [Write, Description("Specifies the name of the certificate to use for HTTPS bindings and service communication for ADFS. This value should match the thumbprint of a valid certificate in the Local Computer certificate store.")] String CertificateName;
>     [Write, Description("Specifies the name of the signing certificate for ADFS. This value should match the name of a valid certificate in the Local Computer certificate store.")] String SigningCertificateName;
>     [Write, Description("Specifies the name of the decryption certificate for ADFS. This value should match the name of a valid certificate in the Local Computer certificate store.")] String DecryptionCertificateName;
> ```

We should call this parameter `DecryptionCertifcateDnsName` here and everywhere referenced and update the description to "...This value should match the DNS name of a valid certificate..."

**Comment by heinejeppesen** [comment]
Hi,

I'm trying to do the same (automate AD, ADCS, ADFS) and have stranded in the same way, where providing a thumbprint simply isn't possible, as the certificate is installed in the step before installing ADFS.

So I'm pretty curious if there any update on this PR? ;-)

**Comment by Yvand** [comment]
I never really gave up to work on this PR to complete the tasks, but writing the Pester tests is not my cup of tea.
With that said, I'm using the changes in this PR intensively it and it works like a charm.

**Comment by heinejeppesen** [comment]
> I never really gave up to work on this PR to complete the tasks, but writing the Pester tests is not my cup of tea. With that said, I'm using the changes in this PR intensively it and it works like a charm.

I'm also using the changes you put into this PR now and they do work great, so thanks for that.

Now I just have to make something similar for AdfsApplicationPermission where it only takes an GUID for client identifier.
Need to implement a lookup for name, just like this. ;-)

**Comment by X-Guardian** [comment]
Hi @Yvand, I have made some small changes to your PR branch to fix the HQRM and unit tests that were failing. If you want to now look at the comments I made previously, we can get this PR ready for merging.

Regarding the Unit test coverage, I can add a couple of tests to cover your new code if you are not comfortable doing that.

**Comment by Yvand** [comment]
@X-Guardian thank you, I'm checking now

**Comment by Yvand** [comment]
@X-Guardian I tested it in 2 deployments, it works like a charm

**Comment by X-Guardian** [comment]
@Yvand, can you look at the review comments I made on April 11th 2021. You can click on the `Reviewable` button to see these annotated on the code.

**Comment by Yvand** [comment]
@X-Guardian now I see those comments, I'm not familiar with Reviewable and completely missed them.
I'll clone the PR branch to my machine and review them asap, probably but maybe not today

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-guardian/adfsdsc/48)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @X-Guardian)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 113 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-wszx8AAXhueGxGOi:-NLfOXPR3q799TOxx5de:b-896fix) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L113)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

`CertificateName` and `CertificateThumbprint` are no longer needed as parameters on `Get-TargetResource` as they are not mandatory.
</blockquote></details>

Done.

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @X-Guardian)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 113 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY-wszx8AAXhueGxGOi:-NLyyBIVDQroFRk9Ly87:b-v64eyy) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L113)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry I don't understand the ask here. If I remove parameters $CertificateThumbprint and $CertificateName from Get-TargetResource, then can this not cause an exception in $returnValue (because they may not even exist)? Or will they simply be considered $null ?
___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 214 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY-xnja439qpos1jPC8:-NLz2nbf6Jc7AF2jiRV8:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L214)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Need to add `SigningCertifcateName` and `DecryptionCertificateName` parameters. Values for these can be obtained using the `Get-AdfsCertificate -CertificateType` cmdlet.
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 229 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY-yAbs1oPSDX_wsKl8:-NLz2qgN9PiKL2I28l7n:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L229)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

`CertificateThumbprint` and `CertificateName` should both be returned `$null`. Need to add `SigningCertificateName` and`DecryptionCertificateName`
</blockquote></details>

Done.

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @X-Guardian)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 367 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY-yaN89QTMP94kgh5M:-NM8OajF5FfX50F-OCua:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L367)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

`CertificateName` and `CertiifcateThumbprint` parameters not needed.
</blockquote></details>

Done.

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @X-Guardian)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 395 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY-yfk22L1eOry3S6Me:-NM8hGKk7Mqdz-plUUVh:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L395)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Need to raise an `InvalidArgumentException` if the certificate does not exist. It may also match multiple certificates. Suggest logic is added to use the one with the latest `NotAfter` date, as long as the `NotBefore` date has passed.
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 402 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY-yxxQ2aXPdlOxW8dR:-NM8hHCj1pkf3NwiqH8n:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L402)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Need to raise an `InvalidArgumentException` if the certificate does not exist. It may also match multiple certificates. Suggest logic is added to use the one with the latest `NotAfter` date, as long as the `NotBefore` date has passed.
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 409 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY-yyay0TA4xMMkJq9u:-NM8hHcV68yeX3LeL3Ta:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L409)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Need to raise an `InvalidArgumentException` if the certificate does not exist. It may also match multiple certificates. Suggest logic is added to use the one with the latest `NotAfter` date, as long as the `NotBefore` date has passed.
</blockquote></details>

Done.

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @X-Guardian)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof` line 14 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY0ettGAOd3PBaJkxFY:-NM9PpGf0J2Q34M19dCl:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof#L14)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

We should call this parameter `CertifcateDnsName` here and everywhere referenced and update the description to  "...This value should match the DNS name of a valid certificate..."
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof` line 15 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY0f2J41aTuUngVmPQJ:-NM9PoyvD4AbsDznw2YS:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof#L15)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

We should call this parameter `SigningCertifcateDnsName` here and everywhere referenced and update the description to "...This value should match the DNS name of a valid certificate..."
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof` line 16 at r1](https://reviewable.io/reviews/X-Guardian/AdfsDsc/48#-MY0f2nX5ZxtaRMRR3Nh:-NM9Pofb0BwRww2Cv1wI:b-896fix) ([raw file](https://github.com/X-Guardian/AdfsDsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.schema.mof#L16)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

We should call this parameter `DecryptionCertifcateDnsName` here and everywhere referenced and update the description to "...This value should match the DNS name of a valid certificate..."
</blockquote></details>

Done.

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-guardian/adfsdsc/48)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @X-Guardian)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 520 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-z2VL8-UkuurEt9R0:-NM9WF1I1nSyCDCZwG5i:b-896fix) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L520)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

`CertificateName` and `CertiifcateThumbprint` parameters not needed.
</blockquote></details>

Done.

**Comment by Yvand** [comment]
@X-Guardian I think I covered all the changes you requested, but the ui of reviewable is so complicated to understand...
Anyway, waiting on your feedback

**Comment by X-Guardian** [comment]
Thanks @Yvand, I will review and get back to you.

**Comment by Yvand** [comment]
@X-Guardian do you have an update on this PR?

**Review by X-Guardian — COMMENTED** [review]
> Reviewed 1 of 4 files at r7, 5 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/x-guardian/adfsdsc/48)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Yvand)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 113 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-wszx8AAXhueGxGOi:-NNrA-0pEnJhvXVK8oAZ:b9cocpu) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L113)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary><blockquote>

Sorry I don't understand the ask here. If I remove parameters $CertificateThumbprint and $CertificateName from Get-TargetResource, then can this not cause an exception in $returnValue (because they may not even exist)? Or will they simply be considered $null ?
</blockquote></details>

They will be considered $null. Only mandatory parameters should be specified on the `Get` function.

**Comment by X-Guardian** [comment]
Hi @Yvand, I've reviewed your code and added some unit tests for the new functionality and an example. I also made a few small changes to your code. The only significant change was adding a new check so that if either `SigningCertificateDnsName` or `DecryptionCertificateDnsName` were specified, the other parameter also needed to be specified. This is a requirement of the `Install-AdfsFarm` cmdlet.

Can you take a look at my changes and check you are happy with them. We can then get the PR merged and create a preview release for testing through the PowerShell Gallery.

**Comment by Yvand** [comment]
Thank you @X-Guardian 
I'll review/test your changes and come back to you

**Comment by Yvand** [comment]
@X-Guardian I tested with your changes and it works perfectly fine

**Comment by Yvand** [comment]
@X-Guardian is this PR still in your radar?

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/x-guardian/adfsdsc/48)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @X-Guardian)

___
*[`source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1` line 113 at r1](https://reviewable.io/reviews/x-guardian/adfsdsc/48#-MY-wszx8AAXhueGxGOi:-NPr3vcS5V10JtJ1IHgo:b2nhb2c) ([raw file](https://github.com/x-guardian/adfsdsc/blob/55eac98c1af9651b310224997168c43870b6aa24/source/DSCResources/MSFT_AdfsFarm/MSFT_AdfsFarm.psm1#L113)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

They will be considered $null. Only mandatory parameters should be specified on the `Get` function.
</blockquote></details>

Ack

**Review by X-Guardian — COMMENTED** [review]
> Reviewed 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/x-guardian/adfsdsc/48)* status: all files reviewed, 1 unresolved discussion (waiting on @Yvand)

**Comment by X-Guardian** [comment]
Hi @Yvand, I have released [AdfsDsc v1.3.0](https://www.powershellgallery.com/packages/AdfsDsc/1.3.0) to the PowerShell Gallery  which includes this PR. Thanks very much for your contribution.

**Pull request merged**
