### PR TITLE
AdfsServerApplication: Add basic support for AdfsServerApplication

### PR DESCRIPTION
**Pull request by watschi**
#### Pull Request (PR) description
This PR adds basic support for AdfsServerApplication. For authentication of the Server Application only ADUserPrincipalName can be configured for now, client secrets or certificates are not configurable.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/X-Guardian/AdfsDsc/74)

### CODE REVIEW

**Comment by watschi** [comment]
Hi @X-Guardian,

not sure why the pipeline fails, according to a quick google search the download error can be an intermittent node and/or permission issue.
The run on my forked repo went thorugh succesfully:
https://dev.azure.com/fabianwendlandt0807/AdfsDsc/_build/results?buildId=10&view=results

Maybe you can retrigger your pipeline?

Thanks!

**Comment by X-Guardian** [comment]
Still failed after retrying. The delights of Azure DevOps! I'll try and take a look at the pipeline issue later today.

Thanks for the PR @watschi. Nice to know people are using the module.

**Comment by X-Guardian** [comment]
Looks good @watschi. Have you been able to run the integration tests successfully yourself?

**Comment by watschi** [comment]
Hi @X-Guardian, thanks for fixing the pipeline!

I thought integration tests are running in the default test runs, apperantly not.
I did push a configuration to an ADFS farm succesfully, but will run integration tests tomorrow and report the results in here after.
I also noticed an oversight in the localization strings (copied from AdfsNativeClient) which I'll fix.

**Comment by X-Guardian** [comment]
No, the integration tests need an Active Directory, which is tricky to setup in the CI, so have always been run offline manually.

**Comment by watschi** [comment]
Fixed the localization strings as mentioned and was able to run the integration tests succesfully (transcript attached: [adfsdsc_integration.log](https://github.com/X-Guardian/AdfsDsc/files/13113191/adfsdsc_integration.log)).

Please let me know if there's anything else I can help with!

grafik

**Review by X-Guardian — APPROVED** [review]
Looks good @watsch . Thanks for a nice PR.

> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/X-Guardian/AdfsDsc/74#-:-NhXyhoR1YGhf4H20hOI:b-rds1eo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @watschi)

**Comment by X-Guardian** [comment]
Hi @watschi, this has been released in [v1.4.0](https://www.powershellgallery.com/packages/AdfsDsc/1.4.0)

**Comment by watschi** [comment]
Thanks for fixing the pipeline and merging so quickly! :)

**Pull request merged**
